apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels: 
    app : {{ .Values.app.label }}
spec:
  type: {{ .Values.service.type }}
  selector:             
    app: {{ .Values.app.label }}
  ports:
    - port: {{ .Values.service.port }}    
  
