apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.red.name }}
spec:
  type: {{ .Values.service.type }}
  selector:             
    app: {{ .Values.red.label }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
          
  